Algoritmo "potencia"

Var

   base,expoente,resultado,i:real
   numero:inteiro



Inicio

    numero <- 1
   enquanto numero > 0 faca
   
      escreva ("Número base: ")
      leia (base)
      escreva ("Expoente: ")
      leia (expoente)


      resultado <- base ^ expoente

      escreval(resultado)

      escreva ("Digite zero para sair ou 1 para continuar: ")
      leia(numero)
   fimenquanto






Fimalgoritmo